#!/bin/bash
set -e

# Set locale
localectl set-locale LANG=en_GB.UTF-8

# Disable SSH password authentication
sed -i 's/^#\?PasswordAuthentication.*/PasswordAuthentication no/' /etc/ssh/sshd_config
systemctl restart ssh

# Update system and install packages
apt-get update
apt-get upgrade -y
apt-get install -y git ansible

# Run Ansible playbook
ansible-pull -U https://github.com/tekore/Ansible.git -i localhost, --purge playbooks/provisionNewServer.yml
#ansible-pull -U https://github.com/tekore/Ansible.git -i localhost, playbooks/configureLxd.yml --extra-vars "@path/to/your_vars_file.yml"